version: "3"

services:
  mysql:
    image: mysql:latest
    networks:
      - redmine_net
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redminepass

  redmine:
    image: redmine:latest
    depends_on:
      - mysql
    networks:
      - redmine_net
    volumes:
      - redmine_data:/usr/src/redmine/files
    ports:
      - "8081:3000"
    restart: always
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redminepass
networks:
  redmine_net:
volumes:
  mysql_data:
  redmine_data:
