version: '3.8'

# ==============================================
# RecursionCurriculum Java + Spring Boot環境
# 共通データベース（docker-shared）を使用
# ==============================================

services:
  # ==============================================
  # Java開発環境（Spring Boot対応）
  # ==============================================
  java:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recursion-java
    hostname: java-dev
    volumes:
      # Java プロジェクトマウント
      - ../advanced/java:/workspace/advanced/java
      # キャッシュボリューム（永続化）
      - maven-cache:/workspace/.m2
      - gradle-cache:/workspace/.gradle
    working_dir: /workspace/advanced/java
    ports:
      - "9080:8080"    # Spring Boot メインポート
      - "9081:8081"    # 追加アプリケーションポート
      - "5005:5005"    # Java リモートデバッグポート (JDWP)
    environment:
      # Javaデバッグ設定（リモートデバッグ有効化）
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      # Spring Boot 設定
      - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
      - SERVER_PORT=8080
      # Maven/Gradle設定
      - MAVEN_OPTS=-Xmx512m
      - GRADLE_OPTS=-Xmx512m -Dorg.gradle.daemon=false
      # 共通MySQL接続情報
      - SPRING_DATASOURCE_URL=jdbc:mysql://recursion-shared-mysql:3306/recursion_db?useSSL=false&serverTimezone=Asia/Tokyo
      - SPRING_DATASOURCE_USERNAME=recursion_user
      - SPRING_DATASOURCE_PASSWORD=recursion_pass
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      # 共通PostgreSQL接続情報
      - SPRING_DATASOURCE_POSTGRES_URL=jdbc:postgresql://recursion-shared-postgres:5432/recursion_db
      - SPRING_DATASOURCE_POSTGRES_USERNAME=recursion_user
      - SPRING_DATASOURCE_POSTGRES_PASSWORD=recursion_pass
      # JPA設定
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    networks:
      - java-network
      - shared-network
    restart: unless-stopped
    # 開発用：コンテナを起動状態に保つ
    command: ["tail", "-f", "/dev/null"]
    # プロダクション用（コメントアウト）：
    # command: ["java", "-jar", "target/app.jar"]

# ==============================================
# ボリューム定義
# ==============================================
volumes:
  maven-cache:
    driver: local
    name: recursion-maven-cache

  gradle-cache:
    driver: local
    name: recursion-gradle-cache

# ==============================================
# ネットワーク定義
# ==============================================
networks:
  java-network:
    driver: bridge
    name: recursion-java-network

  # 共通ネットワークに参加（docker-sharedで作成済み）
  shared-network:
    external: true
    name: recursion-shared-network