version: '3.8'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recursion-go
    hostname: go-dev
    volumes:
      - ../lang-training/go:/workspace
      - go-modules:/go/pkg/mod
    working_dir: /workspace
    ports:
      - "8000:8000"
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
      # 共通MySQL接続情報
      - DB_HOST=recursion-shared-mysql
      - DB_PORT=3306
      - DB_DATABASE=recursion_db
      - DB_USERNAME=recursion_user
      - DB_PASSWORD=recursion_pass
    networks:
      - go-network
      - shared-network
    restart: unless-stopped
    command: ["air", "-c", ".air.toml"]

volumes:
  go-modules:
    driver: local
    name: recursion-go-modules

networks:
  go-network:
    driver: bridge
    name: recursion-go-network

  shared-network:
    external: true
    name: recursion-shared-network