version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recursion-python
    hostname: python-dev
    volumes:
      - ../video-compressor/python:/workspace
      - pip-cache:/root/.cache/pip
    working_dir: /workspace
    ports:
      - "5000:5000"  # Flask
      - "5001:8000"  # FastAPI/Uvicorn
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      # 共通MySQL接続情報
      - DB_HOST=recursion-shared-mysql
      - DB_PORT=3306
      - DB_DATABASE=recursion_db
      - DB_USER=recursion_user
      - DB_PASSWORD=recursion_pass
      # 共通PostgreSQL接続情報
      - POSTGRES_HOST=recursion-shared-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=recursion_db
      - POSTGRES_USER=recursion_user
      - POSTGRES_PASSWORD=recursion_pass
    networks:
      - python-network
      - shared-network
    restart: unless-stopped
    command: ["python", "-u", "server.py"]

volumes:
  pip-cache:
    driver: local
    name: recursion-pip-cache

networks:
  python-network:
    driver: bridge
    name: recursion-python-network

  shared-network:
    external: true
    name: recursion-shared-network