version: '3.8'

services:
  typescript:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recursion-typescript
    hostname: typescript-dev
    volumes:
      - ../lang-training/typescript:/workspace
      - node-modules:/workspace/node_modules
      - npm-cache:/root/.npm
    working_dir: /workspace
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      # 共通MySQL接続情報
      - DB_HOST=recursion-shared-mysql
      - DB_PORT=3306
      - DB_DATABASE=recursion_db
      - DB_USER=recursion_user
      - DB_PASSWORD=recursion_pass
      # 共通PostgreSQL接続情報
      - POSTGRES_HOST=recursion-shared-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=recursion_db
      - POSTGRES_USER=recursion_user
      - POSTGRES_PASSWORD=recursion_pass
    networks:
      - typescript-network
      - shared-network
    restart: unless-stopped
    command: ["npm", "run", "dev"]

volumes:
  node-modules:
    driver: local
    name: recursion-node-modules

  npm-cache:
    driver: local
    name: recursion-npm-cache

networks:
  typescript-network:
    driver: bridge
    name: recursion-typescript-network

  shared-network:
    external: true
    name: recursion-shared-network